import { expect, mock, test } from 'claude-code/testing'
import { cells, percent, remaining } from '../hooks/helpers'
test('percent clamps invalid and extreme API values',async()=>{
 expect(percent(NaN)).toBe(null);expect(percent('50')).toBe(null)
 expect(percent(-20)).toBe(0);expect(percent(120)).toBe(100);expect(cells(100,4)).toBe('▪▪▪▪')
})
test('reset accepts seconds, milliseconds and ISO',async()=>{
 const now=1700000000000
 expect(remaining((now+120000)/1000,now)).toBe('2м')
 expect(remaining(now+120000,now)).toBe('2м')
 expect(remaining(new Date(now+120000).toISOString(),now)).toBe('2м')
 expect(remaining('nonsense',now)).toBe('')
})
test('no invented cache TTL; display settings survive',async($,on)=>{
 const store=new Map()
 mock.clock(on,{now:5000})
 on('store.get',($,e)=>({value:store.get(e.key)}))
 on('store.set',($,e)=>{store.set(e.key,e.value);return {value:undefined}})
 on('session.start',()=>({cwd:'/work'}))
 on('session.usage',()=>({value:{context:{percent:41},rateLimits:[]}}))
 on('command.register',()=>({value:undefined}))
 on('ui.status',()=>({value:undefined}))
 await $.session.start({surface:'terminal',isInteractive:true,cwd:'/work'})
 expect((await $.command.run({command:'ctx'})).text).not.toContain('кэш')
 await $.command.run({command:'ctx',args:'cache 5'})
 expect(store.get('display').cacheTTL).toBe(5)
 await $.command.run({command:'ctx',args:'hide'})
 expect(store.get('display').hidden).toBe(true)
 await $.command.run({command:'ctx',args:'cache off'})
 expect(store.get('display').cacheTTL).toBe(null)
})

test('cache estimate resets after clear; new timer replaces old one',async($,on)=>{
 const clock=mock.clock(on,{now:5000});const store=new Map();let measures=0
 on('store.get',($,e)=>({value:store.get(e.key)}))
 on('store.set',($,e)=>{store.set(e.key,e.value);return {value:undefined}})
 on('session.start',()=>({cwd:'/work'}))
 on('session.usage',()=>{measures++;return {value:{context:{percent:50},rateLimits:[]}}})
 on('command.register',()=>({value:undefined}))
 on('command.run',()=>({text:''}))
 on('ui.status',()=>({value:undefined}))
 on('turn.step',async function*($,e){return {turnId:e.turnId,index:0,answer:'ok',toolUses:[],stopReason:'end_turn',usage:null}})
 await $.session.start({surface:'terminal',isInteractive:true,cwd:'/work'})
 await $.command.run({command:'ctx',args:'cache 5'})
 const stream=$.turn.step({turnId:'t',index:0,model:'test',messageCount:1})
 let step=await stream.next();while(!step.done) step=await stream.next()
 expect((await $.command.run({command:'ctx'})).text).toContain('кэш ≈5м')
 await $.command.run({command:'clear'})
 expect((await $.command.run({command:'ctx'})).text).not.toContain('кэш')
 await $.session.start({surface:'terminal',isInteractive:true,cwd:'/work'})
 const before=measures
 await clock.advance(30000)
 expect(measures-before).toBe(1)
})
test('prompt hint renders context in narrow terminal',async($,on)=>{
 mock.clock(on,{now:5000});mock.store(on)
 on('session.start',()=>({cwd:'/work'}))
 on('session.usage',()=>({value:{context:{percent:91},rateLimits:[]}}))
 on('command.register',()=>({value:undefined}))
 on('ui.status',()=>({value:undefined}))
 await $.session.start({surface:'terminal',isInteractive:true,cwd:'/work'})
 const ui=await $.ui.mount({plugin:'ctx',component:'PromptHint',surface:'terminal',viewport:{columns:40,rows:20},props:{isDraft:false}})
 expect(await ui.find({type:'Text',text:/CTX 91%/})).toBeDefined()
 await ui.unmount()
})
